application:
  name: simple-example-node-with-postgresql
  project: simple-example-node-with-postgresql
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-3498225
routers:
- name: main
  custom_domains:
  - domain: "node.deimos.fr"
  routes:
  - application_name: simple-example-node-with-postgresql
    paths:
    - /
